//
//  LMBrowsingDetailView.m
//  Lignite Music
//
//  Created by Edwin Finch on 11/11/16.
//  Copyright © 2016 Lignite. All rights reserved.
//

#import <ApIdleManager/APIdleManager.h>
#import <PureLayout/PureLayout.h>
#import "LMBrowsingDetailViewController.h"
#import "LMTiledAlbumCoverView.h"
#import "LMBrowsingDetailView.h"
#import "LMNowPlayingView.h"
#import "LMLayoutManager.h"
#import "LMBigListEntry.h"
#import "LMMusicPlayer.h"
#import "LMListEntry.h"
#import "LMColour.h"
#import "LMExtras.h"

@interface LMBrowsingDetailView()<LMTableViewSubviewDataSource, LMBigListEntryDelegate, LMCollectionInfoViewDelegate, LMListEntryDelegate, LMMusicPlayerDelegate, LMControlBarViewDelegate, UITableViewDelegate, LMLayoutChangeDelegate>

@property LMBigListEntry *headerBigListEntry;
@property NSMutableArray *songEntries;

@property float largeSize;

@property LMMusicPlayer *musicPlayer;

@property NSInteger currentlyHighlighted;

/**
 The specific track collections associated with this browsing view. For example, an artist would have their albums within this array of collections.
 */
@property NSArray<LMMusicTrackCollection*>* specificTrackCollections;

/**
 The background imageView for the album art which will initially be partially covered.
 */
@property UIImageView *backgroundImageView;

/**
 The background tile for for music which is not artist based.
 */
@property LMTiledAlbumCoverView *backgroundTileView;

/**
 The control bar.
 */
@property LMControlBarView *controlBar;

/**
 The last point in scrolling where the user stopped scrolling.
 */
@property CGPoint lastScrollingOffsetPoint;

/**
 Whether or not the scrolling that the user did broke the treshhold for minimizing the bottom button bar.
 */
@property BOOL brokeScrollingThreshhold;

/**
 The layout manager.
 */
@property LMLayoutManager *layoutManager;

/**
 Landscape views which are generated by the table view on reload and need to be released on dealloc from the layout manager.
 */
@property NSMutableArray *landscapeViewsToRelease;

/**
 The control bar which goes below the content view in landscape mode.
 */
@property LMControlBarView *landscapeControlBar;

@end

@implementation LMBrowsingDetailView

- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
	CGFloat difference = fabs(scrollView.contentOffset.y-self.lastScrollingOffsetPoint.y);
	if(difference > WINDOW_FRAME.size.height/4){
		self.brokeScrollingThreshhold = YES;
		[self.rootViewController.buttonNavigationBar minimize];
	}
	
	[[APIdleManager sharedInstance] didReceiveInput];
}

- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate {
	if(self.brokeScrollingThreshhold){
		//[self.rootViewController.buttonNavigationBar minimize];
	}
	self.brokeScrollingThreshhold = NO;
	self.lastScrollingOffsetPoint = scrollView.contentOffset;
}

- (void)musicPlaybackStateDidChange:(LMMusicPlaybackState)newState {
	NSLog(@"Playback state changed in browsing detail view delegate");
	[self.controlBar reloadHighlightedButtons];
	
}

- (LMListEntry*)listEntryForIndex:(NSInteger)index {
	if(index == -1){
		return nil;
	}
	
	LMListEntry *entry = nil;
	for(int i = 0; i < self.songEntries.count; i++){
		LMListEntry *indexEntry = [self.songEntries objectAtIndex:i];
		if(indexEntry.collectionIndex == index){
			entry = indexEntry;
			break;
		}
	}
	return entry;
}

- (void)musicTrackDidChange:(LMMusicTrack*)newTrack {
	LMListEntry *highlightedEntry = nil;
	int newHighlightedIndex = -1;
	if(self.specificTrackCollections){
		int count = 0;
		for(LMMusicTrackCollection *collection in self.specificTrackCollections){
			for(LMMusicTrack *track in collection.items){
				if(track.persistentID == newTrack.persistentID){
					newHighlightedIndex = count;
					NSLog(@"Found a match");
				}
			}
			count++;
		}
	}
	else{
		for(int i = 0; i < self.musicTrackCollection.trackCount; i++){
			LMMusicTrack *track = [self.musicTrackCollection.items objectAtIndex:i];
			
			if(track.persistentID == newTrack.persistentID){
				newHighlightedIndex = i;
			}
		}
	}
	
	highlightedEntry = [self listEntryForIndex:newHighlightedIndex];
	
	LMListEntry *previousHighlightedEntry = [self listEntryForIndex:self.currentlyHighlighted];
	if(![previousHighlightedEntry isEqual:highlightedEntry] || highlightedEntry == nil){
		[previousHighlightedEntry changeHighlightStatus:NO animated:YES];
		BOOL updateNowPlayingStatus = self.currentlyHighlighted == -1;
		self.currentlyHighlighted = newHighlightedIndex;
		if(updateNowPlayingStatus){
			[self musicPlaybackStateDidChange:self.musicPlayer.playbackState];
		}
	}
	
	if(highlightedEntry){
		[highlightedEntry changeHighlightStatus:YES animated:YES];
	}
}

- (void)musicPlaybackModesDidChange:(LMMusicShuffleMode)shuffleMode repeatMode:(LMMusicRepeatMode)repeatMode {
	[self.controlBar reloadHighlightedButtons];
}

- (void)musicLibraryDidChange {
	[(UINavigationController*)self.window.rootViewController popViewControllerAnimated:YES];
}

- (UIImage*)imageWithIndex:(uint8_t)index forControlBarView:(LMControlBarView *)controlBar {
	switch(index){
		case 0:{
			BOOL isPlaying = [self.musicPlayer.nowPlayingCollection isEqual:self.musicTrackCollection] && self.musicPlayer.playbackState == LMMusicPlaybackStatePlaying;
			
			return [LMAppIcon invertImage:[LMAppIcon imageForIcon:isPlaying ? LMIconPause : LMIconPlay]];
		}
		case 1:{
			return [LMAppIcon imageForIcon:LMIconRepeat];
		}
		case 2:{
			return [LMAppIcon imageForIcon:LMIconShuffle];
		}
	}
	return [LMAppIcon imageForIcon:LMIconBug];
}

- (BOOL)buttonHighlightedWithIndex:(uint8_t)index wasJustTapped:(BOOL)wasJustTapped forControlBar:(LMControlBarView *)controlBar {
	BOOL isPlayingMusic = (self.musicPlayer.playbackState == LMMusicPlaybackStatePlaying);
	
	switch(index) {
		case 0:{ //Play button
			LMMusicTrackCollection *trackCollection = self.musicTrackCollection;
			if(wasJustTapped){
				if(trackCollection.trackCount > 0){
					if(self.musicPlayer.nowPlayingCollection != trackCollection){
						self.musicPlayer.autoPlay = YES;
						isPlayingMusic = YES;
						[self.musicPlayer setNowPlayingCollection:trackCollection];
						
						[self.musicPlayer.navigationBar setSelectedTab:LMNavigationTabMiniplayer];
						[self.musicPlayer.navigationBar maximize];
					}
					else{
						isPlayingMusic ? [self.musicPlayer pause] : [self.musicPlayer play];
						isPlayingMusic = !isPlayingMusic;
					}
				}
				return isPlayingMusic;
			}
			else{
				return [self.musicPlayer.nowPlayingCollection isEqual:trackCollection] && isPlayingMusic;
			}
		}
		case 1: //Repeat button
			if(wasJustTapped){
				(self.musicPlayer.repeatMode == LMMusicRepeatModeAll)
					? (self.musicPlayer.repeatMode = LMMusicRepeatModeNone)
					: (self.musicPlayer.repeatMode = LMMusicRepeatModeAll);
			}
			NSLog(@"Repeat mode is %d", self.musicPlayer.repeatMode);
			return (self.musicPlayer.repeatMode == LMMusicRepeatModeAll);
		case 2: //Shuffle button
			if(wasJustTapped){
				self.musicPlayer.shuffleMode = !self.musicPlayer.shuffleMode;
			}
			NSLog(@"Shuffle mode is %d", self.musicPlayer.shuffleMode);
			return (self.musicPlayer.shuffleMode == LMMusicShuffleModeOn);
	}
	return YES;
}

- (uint8_t)amountOfButtonsForControlBarView:(LMControlBarView *)controlBar {
	return 3;
}

- (NSString*)titleForInfoView:(LMCollectionInfoView*)infoView {
	switch(self.musicType){
		case LMMusicTypeCompilations:
		case LMMusicTypeGenres:
		case LMMusicTypePlaylists: {
			return [self.musicTrackCollection titleForMusicType:self.musicType];
		}
		case LMMusicTypeAlbums: {
			return self.musicTrackCollection.representativeItem.albumTitle ? self.musicTrackCollection.representativeItem.albumTitle : NSLocalizedString(@"UnknownAlbum", nil);
		}
		case LMMusicTypeComposers: {
			return self.musicTrackCollection.representativeItem.composer ? self.musicTrackCollection.representativeItem.composer : NSLocalizedString(@"UnknownComposer", nil);
		}
		case LMMusicTypeArtists: {
			return self.musicTrackCollection.representativeItem.artist ? self.musicTrackCollection.representativeItem.artist : NSLocalizedString(@"UnknownArtist", nil);
		}
		default:{
			return nil;
		}
	}
}

- (NSString*)leftTextForInfoView:(LMCollectionInfoView*)infoView {
	switch(self.musicType){
		case LMMusicTypeComposers:
		case LMMusicTypeArtists: {
			if(self.specificTrackCollections){
				return [NSString stringWithFormat:@"%lu %@", (unsigned long)self.specificTrackCollections.count, NSLocalizedString(self.specificTrackCollections.count == 1 ? @"AlbumInline" : @"AlbumsInline", nil)];
			}
			else{
				return [NSString stringWithFormat:@"%lu %@", (unsigned long)self.musicTrackCollection.numberOfAlbums, NSLocalizedString(self.musicTrackCollection.numberOfAlbums == 1 ? @"AlbumInline" : @"AlbumsInline", nil)];
			}
		}
		case LMMusicTypeGenres:
		case LMMusicTypePlaylists: {
			return [NSString stringWithFormat:@"%ld %@", self.musicTrackCollection.trackCount, NSLocalizedString(self.musicTrackCollection.trackCount == 1 ? @"Song" : @"Songs", nil)];
		}
		case LMMusicTypeCompilations:
		case LMMusicTypeAlbums: {
			if(self.musicTrackCollection.variousArtists){
				return NSLocalizedString(@"Various", nil);
			}
			return self.musicTrackCollection.representativeItem.artist ? self.musicTrackCollection.representativeItem.artist : NSLocalizedString(@"UnknownArtist", nil);
		}
		default: {
			return nil;
		}
	}
}

- (NSString*)rightTextForInfoView:(LMCollectionInfoView*)infoView {
	switch(self.musicType){
		case LMMusicTypeComposers:
		case LMMusicTypeArtists: {
			return [NSString stringWithFormat:@"%ld %@", self.musicTrackCollection.trackCount, NSLocalizedString(self.musicTrackCollection.trackCount == 1 ? @"Song" : @"Songs", nil)];
		}
		case LMMusicTypeGenres:
		case LMMusicTypePlaylists: {
			return nil;
		}
		case LMMusicTypeCompilations:
		case LMMusicTypeAlbums: {
			return [NSString stringWithFormat:@"%ld %@", self.musicTrackCollection.trackCount, NSLocalizedString(self.musicTrackCollection.trackCount == 1 ? @"Song" : @"Songs", nil)];
		}
		default: {
			return nil;
		}
	}
}

- (UIImage*)centerImageForInfoView:(LMCollectionInfoView*)infoView {
	return nil;
}

- (id)contentSubviewForBigListEntry:(LMBigListEntry*)bigListEntry {
	switch(self.musicType){
		case LMMusicTypeGenres:
		case LMMusicTypePlaylists: {
			LMTiledAlbumCoverView *tiledAlbumCover = [LMTiledAlbumCoverView newAutoLayoutView];
			tiledAlbumCover.musicCollection = self.musicTrackCollection;
			return tiledAlbumCover;
		}
		case LMMusicTypeCompilations:
		case LMMusicTypeAlbums: {
			UIImageView *imageView = [UIImageView newAutoLayoutView];
			imageView.contentMode = UIViewContentModeScaleAspectFit;
			imageView.image = [self.musicTrackCollection.representativeItem albumArt];
			return imageView;
		}
		case LMMusicTypeComposers:
		case LMMusicTypeArtists: {
			UIImageView *imageView = [UIImageView newAutoLayoutView];
			imageView.contentMode = UIViewContentModeScaleAspectFit;
			imageView.image = [self.musicTrackCollection.representativeItem artistImage];
			return imageView;
		}
		default: {
			return nil;
		}
	}
}

- (float)contentSubviewFactorial:(BOOL)height forBigListEntry:(LMBigListEntry *)bigListEntry {
	switch(self.musicType){
		case LMMusicTypeGenres:
		case LMMusicTypePlaylists:
//		{
//			return height ? 0.25 : 0.80;
//		}
		case LMMusicTypeComposers:
		case LMMusicTypeArtists:
		case LMMusicTypeCompilations:
		case LMMusicTypeAlbums: {
			return height ? WINDOW_FRAME.size.width/WINDOW_FRAME.size.height : 1.0; //To fill to the edge of the screen
		}
		default: {
			return 0.50;
		}
	}
}

- (void)sizeChangedToLargeSize:(BOOL)largeSize withHeight:(float)newHeight forBigListEntry:(LMBigListEntry*)bigListEntry {
	if(largeSize){
		self.largeSize = newHeight;
	}
	[self.tableView reloadSubviewSizes];
}

- (void)tappedListEntry:(LMListEntry*)entry {
	if(self.specificTrackCollections){
		LMMusicTrackCollection *collection = [self.specificTrackCollections objectAtIndex:entry.collectionIndex];
		
		LMBrowsingDetailViewController *browsingDetailController = [LMBrowsingDetailViewController new];
		browsingDetailController.browsingDetailView = [LMBrowsingDetailView newAutoLayoutView];
		browsingDetailController.browsingDetailView.musicType = LMMusicTypeAlbums;
		browsingDetailController.browsingDetailView.musicTrackCollection = collection;
		browsingDetailController.browsingDetailView.rootViewController = self.rootViewController;
		[self.rootViewController showViewController:browsingDetailController sender:self];
		return;
	}
	LMMusicTrack *track = [self.musicTrackCollection.items objectAtIndex:entry.collectionIndex];
	
	LMListEntry *previousHighlightedEntry = [self listEntryForIndex:self.currentlyHighlighted];
	if(previousHighlightedEntry){
		[previousHighlightedEntry changeHighlightStatus:NO animated:YES];
	}
	
	[entry changeHighlightStatus:YES animated:YES];
	self.currentlyHighlighted = entry.collectionIndex;
	
	if(self.musicPlayer.nowPlayingCollection != self.musicTrackCollection){
#ifdef SPOTIFY
		[self.musicPlayer pause];
#else
		[self.musicPlayer stop];
#endif
		[self.musicPlayer setNowPlayingCollection:self.musicTrackCollection];
	}
	self.musicPlayer.autoPlay = YES;
	
	[self.musicPlayer setNowPlayingTrack:track];
}

- (UIColor*)tapColourForListEntry:(LMListEntry*)entry {
	return [LMColour ligniteRedColour];
}

- (NSString*)titleForListEntry:(LMListEntry*)entry {
	if(self.specificTrackCollections){
		LMMusicTrackCollection *collection = [self.specificTrackCollections objectAtIndex:entry.collectionIndex];
		return collection.representativeItem.albumTitle ? collection.representativeItem.albumTitle : NSLocalizedString(@"UnknownAlbum", nil);
	}
	LMMusicTrack *track = [self.musicTrackCollection.items objectAtIndex:entry.collectionIndex];
	return track.title;
}

- (NSString*)subtitleForListEntry:(LMListEntry*)entry {
	if(self.specificTrackCollections){
		LMMusicTrackCollection *collection = [self.specificTrackCollections objectAtIndex:entry.collectionIndex];
		return [NSString stringWithFormat:@"%ld %@", collection.trackCount, NSLocalizedString(collection.trackCount == 1 ? @"Song" : @"Songs", nil)];
	}
	LMMusicTrack *track = [self.musicTrackCollection.items objectAtIndex:entry.collectionIndex];
	if(self.musicTrackCollection.variousArtists){
		if(self.musicType == LMMusicTypePlaylists){
			return [NSString stringWithFormat:@"#%ld | %@ | %@", (entry.collectionIndex + 1), [LMNowPlayingView durationStringTotalPlaybackTime:track.playbackDuration], track.artist ? track.artist : NSLocalizedString(@"UnknownArtist", nil)];
		}
		else{
			return [NSString stringWithFormat:@"%@ | %@", [LMNowPlayingView durationStringTotalPlaybackTime:track.playbackDuration], track.artist ? track.artist : NSLocalizedString(@"UnknownArtist", nil)];
		}
	}
	else{
		return [LMNowPlayingView durationStringTotalPlaybackTime:track.playbackDuration];
	}
}

- (UIImage*)iconForListEntry:(LMListEntry*)entry {
	if(self.specificTrackCollections){
		LMMusicTrackCollection *collection = [self.specificTrackCollections objectAtIndex:entry.collectionIndex];
		return [collection.representativeItem albumArt];
	}
	LMMusicTrack *track = [self.musicTrackCollection.items objectAtIndex:entry.collectionIndex];
	return [track albumArt];
}

- (NSString*)textForListEntry:(LMListEntry *)entry {
	if(self.musicType == LMMusicTypeAlbums || self.musicType == LMMusicTypeCompilations){
		return [NSString stringWithFormat:@"%ld", entry.collectionIndex+1];
	}
	return @":)";
}

- (id)subviewAtIndex:(NSUInteger)index forTableView:(LMTableView*)tableView {
	if(index == 0){
		UIView *testView = [UIView newAutoLayoutView];
		testView.backgroundColor = [UIColor clearColor];
		return testView;
	}
	if(index == 1){
		UIView *rootView = [UIView newAutoLayoutView];
		
		LMCollectionInfoView *collectionInfoView = [LMCollectionInfoView newAutoLayoutView];
		collectionInfoView.delegate = self;
		collectionInfoView.largeMode = YES;
		[rootView addSubview:collectionInfoView];
		
		[collectionInfoView autoPinEdgeToSuperviewEdge:ALEdgeLeading];
		[collectionInfoView autoPinEdgeToSuperviewEdge:ALEdgeTrailing];
		[collectionInfoView autoPinEdgeToSuperviewEdge:ALEdgeTop];
		
		NSArray *collectionInfoViewPortraitConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
			[collectionInfoView autoMatchDimension:ALDimensionHeight toDimension:ALDimensionHeight ofView:rootView withMultiplier:(6.0/10.0)];
		}];
		[LMLayoutManager addNewPortraitConstraints:collectionInfoViewPortraitConstraints];
		
		NSArray *collectionInfoViewLandscapeConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
			[collectionInfoView autoMatchDimension:ALDimensionHeight toDimension:ALDimensionHeight ofView:rootView];
		}];
		[LMLayoutManager addNewLandscapeConstraints:collectionInfoViewLandscapeConstraints];
		
		collectionInfoView.layer.shadowColor = [UIColor blackColor].CGColor;
		collectionInfoView.layer.shadowRadius = (self.layoutManager.isLandscape ? WINDOW_FRAME.size.width : WINDOW_FRAME.size.height)/35;
		collectionInfoView.layer.shadowOffset = CGSizeMake(0, collectionInfoView.layer.shadowRadius/2);
		collectionInfoView.layer.shadowOpacity = 0.10f;
		
		[collectionInfoView reloadData];
		
		
		LMControlBarView *controlBar = [LMControlBarView newAutoLayoutView];
		controlBar.delegate = self;
		[rootView addSubview:controlBar];
		
		NSArray *controlBarPortraitConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
			[controlBar autoPinEdgeToSuperviewEdge:ALEdgeLeading];
			[controlBar autoPinEdgeToSuperviewEdge:ALEdgeTrailing];
			[controlBar autoPinEdgeToSuperviewEdge:ALEdgeBottom];
			[controlBar autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:collectionInfoView];
		}];
		[LMLayoutManager addNewPortraitConstraints:controlBarPortraitConstraints];
		
		NSArray *controlBarLandscapeConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
			[controlBar autoSetDimension:ALDimensionHeight toSize:CGFLOAT_MIN];
		}];
		[LMLayoutManager addNewLandscapeConstraints:controlBarLandscapeConstraints];
		
		self.controlBar = controlBar;
		
		for(UIView *view in self.landscapeViewsToRelease){
			if(view != controlBar && view != collectionInfoView){
				view.hidden = YES;
				[view removeFromSuperview];
				[LMLayoutManager removeAllConstraintsRelatedToView:view];
			}
		}
		[self.landscapeViewsToRelease removeAllObjects];
		
		[self.landscapeViewsToRelease addObject:collectionInfoView];
		[self.landscapeViewsToRelease addObject:controlBar];
		
		return rootView;
	}
	LMListEntry *listEntry = [self.songEntries objectAtIndex:(index-2) % self.songEntries.count];
	listEntry.collectionIndex = index-2; //To adjust for the big list entry at the top
	if(self.specificTrackCollections) {
		listEntry.associatedData = [self.specificTrackCollections objectAtIndex:listEntry.collectionIndex];
	}
	else{
		listEntry.associatedData = [self.musicTrackCollection.items objectAtIndex:listEntry.collectionIndex];
	}
	[listEntry changeHighlightStatus:self.currentlyHighlighted == listEntry.collectionIndex animated:NO];
	[listEntry reloadContents];
	return listEntry;
}

- (float)heightAtIndex:(NSUInteger)index forTableView:(LMTableView*)tableView {
	if(index == 0){
		return self.layoutManager.isLandscape ? CGFLOAT_MIN : self.frame.size.width;
	}
	if(index == 1){
		//The size of the info view text + the size of the new control bar
		return self.frame.size.height/8.0 + self.frame.size.height/9.0;
	}
	return (self.layoutManager.isLandscape ? WINDOW_FRAME.size.width : WINDOW_FRAME.size.height)/8.0;
}

- (float)spacingAtIndex:(NSUInteger)index forTableView:(LMTableView*)tableView {
	if(index == 0 || index == 1){
		return 0;
	}
	return 10;
}

- (void)amountOfObjectsRequiredChangedTo:(NSUInteger)amountOfObjects forTableView:(LMTableView*)tableView {
	self.songEntries = [NSMutableArray new];
	
	NSUInteger countToUse = self.specificTrackCollections ? self.specificTrackCollections.count : self.musicTrackCollection.trackCount;
	for(int i = 0; i < MIN(amountOfObjects, countToUse); i++){
		LMListEntry *listEntry = [LMListEntry newAutoLayoutView];
		listEntry.delegate = self;
		listEntry.collectionIndex = i;
		listEntry.associatedData = self.specificTrackCollections ?
									[self.specificTrackCollections objectAtIndex:i] :
									[self.musicTrackCollection.items objectAtIndex:i];
		listEntry.isLabelBased = (self.musicType == LMMusicTypeAlbums || self.musicType == LMMusicTypeCompilations);
		[listEntry setup];
		
		[self.songEntries addObject:listEntry];
	}
}

- (void)rootViewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
	[coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
		
	} completion:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
		if(self.musicType != LMMusicTypeArtists){
			[self.backgroundTileView setMusicCollection:self.backgroundTileView.musicCollection];
		}
	}];
}

- (void)setup {
	self.currentlyHighlighted = -1;
	
	self.landscapeViewsToRelease = [NSMutableArray new];
	
	self.layoutManager = [LMLayoutManager sharedLayoutManager];
	[self.layoutManager addDelegate:self];
	
	CGFloat properNumber = (self.layoutManager.isLandscape ? WINDOW_FRAME.size.width : WINDOW_FRAME.size.height);
	
	self.backgroundColor = [UIColor whiteColor];
	
	self.musicPlayer = [LMMusicPlayer sharedMusicPlayer];
	
	BOOL usingSpecificTrackCollections = (self.musicType != LMMusicTypePlaylists
										  && self.musicType != LMMusicTypeCompilations
										  && self.musicType != LMMusicTypeAlbums);
	
	if(usingSpecificTrackCollections){
		self.specificTrackCollections = [self.musicPlayer collectionsForRepresentativeTrack:self.musicTrackCollection.representativeItem
																			   forMusicType:self.musicType];
	}
	
	if(self.musicType == LMMusicTypeArtists){
		self.backgroundImageView = [UIImageView newAutoLayoutView];
		self.backgroundImageView.contentMode = UIViewContentModeScaleAspectFit;
		self.backgroundImageView.image = [self.musicTrackCollection.representativeItem artistImage];
		[self addSubview:self.backgroundImageView];
	}
	else{
		self.backgroundTileView = [LMTiledAlbumCoverView newAutoLayoutView];
		self.backgroundTileView.musicCollection = self.musicTrackCollection;
		[self addSubview:self.backgroundTileView];
	}
	
	id viewToPin = (self.musicType == LMMusicTypeArtists) ? self.backgroundImageView : self.backgroundTileView;
	
	NSArray *viewToPinPortraitConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
		[viewToPin autoPinEdgeToSuperviewEdge:ALEdgeLeading];
		[viewToPin autoPinEdgeToSuperviewEdge:ALEdgeTrailing];
		[viewToPin autoPinEdgeToSuperviewEdge:ALEdgeTop];
		[viewToPin autoMatchDimension:ALDimensionHeight toDimension:ALDimensionWidth ofView:self];
	}];
	[LMLayoutManager addNewPortraitConstraints:viewToPinPortraitConstraints];
	
	NSArray *viewToPinLandscapeConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
		[viewToPin autoPinEdgeToSuperviewEdge:ALEdgeLeading];
		[viewToPin autoPinEdgeToSuperviewEdge:ALEdgeTop];
		[viewToPin autoMatchDimension:ALDimensionWidth toDimension:ALDimensionWidth ofView:self withMultiplier:(1.0/2.0)];
		[viewToPin autoMatchDimension:ALDimensionHeight toDimension:ALDimensionWidth ofView:viewToPin];
	}];
	[LMLayoutManager addNewLandscapeConstraints:viewToPinLandscapeConstraints];
	
	
	
	self.landscapeControlBar = [LMControlBarView newAutoLayoutView];
	self.landscapeControlBar.delegate = self;
	[self addSubview:self.landscapeControlBar];
	
	NSArray *landscapeControlBarPortraitConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
		[self.landscapeControlBar autoSetDimension:ALDimensionHeight toSize:CGFLOAT_MIN];
	}];
	[LMLayoutManager addNewPortraitConstraints:landscapeControlBarPortraitConstraints];
	
	NSArray *landscapeControlBarLandscapeConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
		[self.landscapeControlBar autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:viewToPin];
		[self.landscapeControlBar autoPinEdge:ALEdgeLeading toEdge:ALEdgeLeading ofView:viewToPin];
		[self.landscapeControlBar autoPinEdge:ALEdgeTrailing toEdge:ALEdgeTrailing ofView:viewToPin];
		[self.landscapeControlBar autoPinEdgeToSuperviewEdge:ALEdgeBottom];
	}];
	[LMLayoutManager addNewLandscapeConstraints:landscapeControlBarLandscapeConstraints];
	
	
	
	self.tableView = [LMTableView newAutoLayoutView];
    self.tableView.addBottomWhiteSpace = YES;
	self.tableView.secondaryDelegate = self;
	self.tableView.title = @"PlaylistDetailView";
	self.tableView.averageCellHeight = properNumber/20.0;
	self.tableView.totalAmountOfObjects = (self.specificTrackCollections ? self.specificTrackCollections.count : self.musicTrackCollection.trackCount) + 2;
	self.tableView.shouldUseDividers = YES;
	self.tableView.firstEntryClear = YES;
	self.tableView.dividerSectionsToIgnore = @[ @(0), @(1), @(2) ];
	self.tableView.subviewDataSource = self;
	self.tableView.bottomSpacing = properNumber/3.0;
	[self addSubview:self.tableView];
	
	NSLog(@"Items %ld spec %d", self.tableView.totalAmountOfObjects, self.specificTrackCollections ? 1 : 0);
	
	NSArray *tableViewPortraitConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
		[self.tableView autoPinEdgesToSuperviewEdges];
	}];
	[LMLayoutManager addNewPortraitConstraints:tableViewPortraitConstraints];
	
	NSArray *tableViewLandscapeConstraints = [NSLayoutConstraint autoCreateConstraintsWithoutInstalling:^{
		[self.tableView autoPinEdge:ALEdgeLeading toEdge:ALEdgeTrailing ofView:viewToPin];
		[self.tableView autoPinEdgeToSuperviewEdge:ALEdgeTop];
		[self.tableView autoPinEdgeToSuperviewEdge:ALEdgeBottom];
		[self.tableView autoPinEdgeToSuperviewEdge:ALEdgeTrailing];
	}];
	[LMLayoutManager addNewLandscapeConstraints:tableViewLandscapeConstraints];
	
	[self.tableView reloadSubviewData];
	
    NSInteger countOfItems = self.specificTrackCollections ? self.specificTrackCollections.count : self.musicTrackCollection.count;
    
    if(countOfItems < 4){
//        [self.tableView reloadData];
        NSLog(@"Count is fuck %ld with %ld num sex", countOfItems, self.tableView.numberOfSections);
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.tableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:countOfItems-1] atScrollPosition:countOfItems == 1 ? UITableViewScrollPositionMiddle : UITableViewScrollPositionBottom animated:NO];
        });
    }
    else if(!self.layoutManager.isLandscape){
        [self.tableView setContentOffset:CGPointMake(0, WINDOW_FRAME.size.height/2.0)];
    }
	
	[self.musicPlayer addMusicDelegate:self];
	
	[self.rootViewController pushItemOntoNavigationBarWithTitle:[self titleForInfoView:self.headerBigListEntry.collectionInfoView] withNowPlayingButton:YES];
}

- (void)dealloc {
	[LMLayoutManager removeAllConstraintsRelatedToView:(self.musicType == LMMusicTypeArtists) ? self.backgroundImageView : self.backgroundTileView];
	for(UIView *view in self.landscapeViewsToRelease){
		[LMLayoutManager removeAllConstraintsRelatedToView:view];
	}
}

@end
